### PR TITLE
Update Gitlab CI matrix

### PR DESCRIPTION
**Pull request by jpsamaroo**
@maleadt I'd also like to move OpenCL.jl to the v6 templates if possible. Do you have any examples of using v6 with two different images for NV vs. AMD test steps?

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Interestingly, NV passes on 1.0/1.1/dev, but fails on 1.2/1.3 in a `transpose` of `CLArray`s.

**Comment by maleadt** [comment]
> @maleadt I'd also like to move OpenCL.jl to the v6 templates if possible. Do you have any examples of using v6 with two different images for NV vs. AMD test steps?

You can specify `image` in the job, if that's what you mean. Check e.g. CUDA.jl's .gitlab-ci.yml, where globally a ubuntu image is used, and an nvidia image for the cuda:none target.

The old CI stuff currently used here is unmaintained.

**Comment by jpsamaroo** [comment]
Will do!

> The old CI stuff currently used here is unmaintained.

Yeah, this will need to be fixed up to get things working again. I'll get things sorted out!

**Comment by juliohm** [comment]
Closing as we are using buildkite now.

**Pull request closed without merging**
