### PR TITLE
fix syntax

### PR DESCRIPTION
**Pull request by vchuravy**
Travis was failing, while succeeding so the tests on a few PRs were not run. This fixes up most of the except the CLArray tests. If I have time later today I will look into that

### CODE REVIEW

**Comment by vchuravy** [comment]
Travis is oom due to #83 @dfdx Could you look into that?

**Comment by dfdx** [comment]
Sure, I'll take a look at it today.

**Comment by dfdx** [comment]
Hmm, I may be looking at wrong place, but I see only test failures for `OpenCL.Event`. E.g. see [this](https://travis-ci.org/JuliaGPU/OpenCL.jl/jobs/89783997#L143) log snippet: 

```
OpenCL.Event
  > OpenCL.Event status
  > OpenCL.Event wait
  > OpenCL.Event callback
ERROR: LoadError: LoadError: MethodError: `convert` has no method matching convert(::Type{Ptr{T}}, ::Base.RefValue{Ptr{Void}})
This may have arisen from a call to the constructor Ptr{T}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  call{T}(::Type{T}, ::Any)
  convert{T}(::Type{T}, ::T)
 [inlined code] from deprecated.jl:417
 in unsafe_convert at no file:416
 in add_callback at /Users/travis/.julia/v0.4/OpenCL/src/event.jl:124
 in anonymous at /Users/travis/.julia/v0.4/OpenCL/test/test_event.jl:89
 in context at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:474
 in anonymous at /Users/travis/.julia/v0.4/OpenCL/test/test_event.jl:60
 in facts at /Users/travis/.julia/v0.4/FactCheck/src/FactCheck.jl:448
 in include at /Users/travis/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
 in include at /Users/travis/julia/lib/julia/sys.dylib
 in include_from_node1 at /Users/travis/julia/lib/julia/sys.dylib
 in process_options at /Users/travis/julia/lib/julia/sys.dylib
 in _start at /Users/travis/julia/lib/julia/sys.dylib
while loading /Users/travis/.julia/v0.4/OpenCL/test/test_event.jl, in expression starting on line 1
while loading /Users/travis/.julia/v0.4/OpenCL/test/runtests.jl, in expression starting on line 28
```

I found an issue in tests with `CLArray` for Julia v0.3, though, I'll fix it tomorrow. 

If you see any other issues with `CLArray` expect for this one, could you please specify a relevant log (or OS / Julia version to test it on)?

**Comment by vchuravy** [comment]
You are looking at the tests from #87, take a look at the tests from this PR

https://travis-ci.org/JuliaGPU/OpenCL.jl/jobs/89782486

**Comment by dfdx** [comment]
Thanks, now I see this error. I remember similar issue in another test, so I think I'll be able to fix it in a day or two.

**Comment by dfdx** [comment]
Should be finally fixed in #93

**Pull request merged**
