### PR TITLE
make CLArray <: AbstractArray

### PR DESCRIPTION
**Pull request by nstiurca**
Based on @dfdx's idea in PR #97, but the tests pass now (at least locally on my machine).

### CODE REVIEW

**Comment by nstiurca** [comment]
Hmm, it looks like there might be an issue with Travis on Linux? I don't think it's anything to do with my PR though since the script is failing on `apt-get`.

**Comment by vchuravy** [comment]
I will look into the travis issue later today/tomorrow.

**Comment by vchuravy** [comment]
Can you rebase after #99 has gone through?

**Comment by jakebolewski** [comment]
Although this is desirable, it seems like there are too many performance pitfalls for `AbstractArray` fallbacks in base.  Have you not run into these issues?

**Comment by vchuravy** [comment]
Additionally we then get to the point where you would want to use CLBLAS to power a lot of these algorithms, but we would not want to depend on it in OpenCL.jl. Maybe that is another argument for moving this to GPUArray (or creating GPUArray.jl)?

cc: @SimonDanisch

**Comment by nstiurca** [comment]
#99 seems to have helped, although there are a lot of the following in the Travis log:

    FATAL: Could not load /lib/modules/2.6.32-042stab108.8/modules.dep: No such file or directory
    Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly

That error keeps popping up with every script in `examples/`, but it looks like they still execute/work correctly.

**Comment by nstiurca** [comment]
As for CLBLAS.jl and performance, I'm still trying to get things to work as opposed to get them to work fast, so I really can't say. I'm actually having a lot of trouble with the underlying `libclBLAS`, so I my need to take up some issues with that package before I get things running nicely in Julia for myself.

For now, I'm happy to have a working `CLArray` even if performance isn't ideal yet.

**Comment by dfdx** [comment]
> Although this is desirable, it seems like there are too many performance pitfalls for AbstractArray fallbacks in base. Have you not run into these issues?

Honestly, I don't think we should worry about performance of GPU-based arrays for non-specific operations - having 2 arrays implementing the same interface doesn't imply that they will be fast for _all_ algorithm (e.g. consider difference between dense and sparse arrays and how it affects performance in different use cases).

**Comment by dfdx** [comment]
> Maybe that is another argument for moving this to GPUArray (or creating GPUArray.jl)?

The argument about dependencies is quite valid, but for me it sounds like a question of expectations. PyOpenCL, Boost.Compute, rust-opencl - all of them have array implementations out of the box (as well as CUDArt.jl has `CudaArray`), so if I were new to the topic, I would _expect_ to find arrays in OpenCL itself. 

Also, I still don't see an easy way to create generic `GPUArray`, covering both - OpenCL and CUDA technologies - and I don't see direct profit for this activity. So it will be quite hard to push it into mine (or someone else's) TODO list.

**Comment by SimonDanisch** [comment]
> I would expect to find arrays in OpenCL itself.

Good point, but easily solved by letting OpenCL re-export the GPUArray types.

The biggest benefit of a general GPUArray interface is that you can write higher level libraries which work for both CUDA/OpenCL or maybe even OpenGL arrays.

> covering both - OpenCL and CUDA technologies

I must admit that there are quite a few pitfalls.
I guess most of the functonality must be implemented in `OpenCL.jl`/`CUDA.jl` in the end, but GPUArrays could support things like boundschecking, memory management, `splice!`, `push!` and a richer indexing API.
If `GPUArrays` would force `OpenCL.jl`/`CUDA.jl` to implement a more similar interface, we'd already
made good step forward (e.g. `free`, minimal inteface for buffer types, etc).

**Comment by dfdx** [comment]
> Good point, but easily solved by letting OpenCL re-export the GPUArray types.

Wouldn't it introduce circular dependency? If not, could you please provide a scratch of `GPUArray` implementation?

> I guess most of the functonality must be implemented in `OpenCL.jl`/`CUDA.jl`

Do you really mean `CUDA.jl` and not `CUDArt.jl`? Seems like the latter is much better adopted (e.g. see `CUFFT.jl`, `CUBLAS.jl`, `CUDNN.jl`, etc.)

**Comment by SimonDanisch** [comment]
I guess I mean `CUDArt.jl` then ;)
I can see if I can clean up `AbstractGPUArrays`.
I've actually implemented a map for OpenGL Arrays lately, so it could be a good point in time.

**Comment by dfdx** [comment]
@SimonDanisch Any news on `AbstractGPUArrays`? If not, can we see a map for it?

**Comment by SimonDanisch** [comment]
Oh... Yeah, I'm currently stuffed with work and prioritize releasing GLVisualize.
I see what I can do tomorrow!

**Comment by dfdx** [comment]
Actually no hurry here, I just wanted to refresh the topic to keep it alive, so please take your time.

**Pull request closed without merging**
