### PR TITLE
Sd/osx

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
This is the isolated version of the osx bug I run into in #146 and will be the place to fix it..

**Comment by jpsamaroo** [comment]
Is this PR still relevant to Julia 1.x and OpenCL master? What was the issue that this PR was intended to fix?

**Comment by vchuravy** [comment]
It was trying to fix some of the alignment issues.

**Comment by juliohm** [comment]
Closing it as too old

**Pull request closed without merging**
