### PR TITLE
Sd 1.0

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Still needs quite a bit of work! 
cc: @juliohm @vchuravy

**Comment by juliohm** [comment]
Thanks @SimonDanisch for giving it a try!

**Comment by salmanulhaq** [comment]
Thanks @SimonDanisch! Does it solve all pre-compilation issues?

**Comment by SimonDanisch** [comment]
tests pass locally, but of course not on CI :D

**Comment by juliohm** [comment]
@SimonDanisch could we maybe merge this into master, and submit another PR to fix the CI builds?

**Comment by SimonDanisch** [comment]
I guess that makes sense

**Pull request merged**
