### PR TITLE
[WIP] Julia v0.4 Compatibility 

### PR DESCRIPTION
**Pull request by vchuravy**
I am working on getting OpenCL.jl to run with Julia v0.4 and this branch will track the changes necessary to do so.

Todo:
  - [ ] String -> AbstractString
  - [ ] Nothing -> Void
  - [ ] Seqfault for callbacks https://travis-ci.org/JuliaGPU/OpenCL.jl/jobs/44025578#L319-L330

### CODE REVIEW

**Comment by thraen** [comment]
Hi, 

is this in progress? Don't get me wrong, I don't intend to rush but rather ask if anything is going on atm. (It's because other things don't work well with my Julia v0.3 and I have to decide whether I am going to get those working with 0.3 or wait for opencl to be ready for 0.4)

**Comment by jakebolewski** [comment]
Hi @thraen,

From my perspective, making things work on the development version of Julia (outside of some core packages) is really a waste of time.  Things break too much and it sucks up a lot of effort for little gain.  I'm curious, what does not work well with v0.3? 

That said, I'm not against a PR to make this work, only that I won't be doing it myself until 0.4 is released.

**Comment by thraen** [comment]
I had pycall issues which I reported. The PyCall author asked me to check with v0.4 and corrected the bug for that version. To be honest, I haven't checked, whether it also got corrected for 0.3.
Also the stack trace is better in 0.4 and I had random lapack errors.

**Comment by jakebolewski** [comment]
closed by #66

**Pull request closed without merging**
