### PR TITLE
fix finalizer missing methods/undefined variables/deprecations

### PR DESCRIPTION
**Pull request by nstiurca**
This fixes some errors introduced in PR #80.

### CODE REVIEW

**Comment by vchuravy** [comment]
Thanks, I am still a bit puzzled (and embarrassed) by how Travis didn't catch this... Especially since all of these are copy and paste mistakes.

**Comment by jakebolewski** [comment]
Hmm, how was this not caught by the tests? @nstiurca thanks for the fix.

**Comment by nstiurca** [comment]
I think maybe the errors happened in the garbage collection thread and
maybe those aren't escalated to the main thread? I don't know much about
how the Julia GC works.

**Comment by jakebolewski** [comment]
Ah yes, all error's in finalizers are swallowed, only the error message is printed.

**Pull request merged**
