### PR TITLE
WIP: Fixes for Julia 1.0

### PR DESCRIPTION
**Pull request by juliohm**
To update the package for Julia v1.0

### CODE REVIEW

**Comment by juliohm** [comment]
The  remaining warnings are due to parametric method syntax and implicit assignments to global variables:

```julia
┌ Warning: Deprecated syntax `parametric method syntax Base.cconvert{T}(::Type{Ptr{CL_user_data_tag}}, obj::T)` around /home/juliohm/.julia/dev/OpenCL/src/api.jl:34.
│ Use `Base.cconvert(#unused#::Type{Ptr{CL_user_data_tag}}, obj::T) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/api.jl:34
┌ Warning: Deprecated syntax `parametric method syntax Base.unsafe_convert{T}(::Type{Ptr{CL_user_data_tag}}, ref::Ref{T})` around /home/juliohm/.julia/dev/OpenCL/src/api.jl:35.
│ Use `Base.unsafe_convert(#unused#::Type{Ptr{CL_user_data_tag}}, ref::Ref{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/api.jl:35
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/context.jl:29.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/context.jl:29
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/queue.jl:3.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/queue.jl:3
┌ Warning: Deprecated syntax `implicit assignment to global variable `properties``.
│ Use `global properties` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `properties``.
│ Use `global properties` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/event.jl:5.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/event.jl:5
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/event.jl:19.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/event.jl:19
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/event.jl:58.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/event.jl:58
┌ Warning: Deprecated syntax `parametric method syntax enqueue_wait_for_events{T <: CLEvent}(q::CmdQueue, wait_for::Vector{T})` around /home/juliohm/.julia/dev/OpenCL/src/event.jl:189.
│ Use `enqueue_wait_for_events(q::CmdQueue, wait_for::Vector{T}) where T <: CLEvent` instead.
└ @ ~/.julia/dev/OpenCL/src/event.jl:189
┌ Warning: Deprecated syntax `implicit assignment to global variable `context``.
│ Use `global context` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `context``.
│ Use `global context` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:3.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:3
┌ Warning: Deprecated syntax `parametric method syntax (::Type{Buffer{T}}){T}(mem_id::CL_mem, retain::Bool, len::Integer)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:11.
│ Use `(::Type{Buffer{T}})(mem_id::CL_mem, retain::Bool, len::Integer) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:11
┌ Warning: Deprecated syntax `parametric method syntax Base.eltype{T}(b::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:32.
│ Use `Base.eltype(b::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:32
┌ Warning: Deprecated syntax `parametric method syntax Base.length{T}(b::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:33.
│ Use `Base.length(b::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:33
┌ Warning: Deprecated syntax `parametric method syntax Base.sizeof{T}(b::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:34.
│ Use `Base.sizeof(b::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:34
┌ Warning: Deprecated syntax `parametric method syntax Base.show{T}(io::IO, b::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:36.
│ Use `Base.show(io::IO, b::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:36
┌ Warning: Deprecated syntax `parametric method syntax Buffer{T}(::Type{T}, ctx::Context, len::Integer = 0; hostbuf = nothing)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:44.
│ Use `Buffer(#s19::Type{T}, ctx::Context, len::Integer = 0; hostbuf = nothing) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:44
┌ Warning: Deprecated syntax `parametric method syntax Buffer{T}(::Type{T}, ctx::Context, mem_flag::Symbol, len::Integer = 0; hostbuf = nothing)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:48.
│ Use `Buffer(#s19::Type{T}, ctx::Context, mem_flag::Symbol, len::Integer = 0; hostbuf = nothing) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:48
┌ Warning: Deprecated syntax `parametric method syntax Buffer{T}(::Type{T}, ctx::Context, mem_flags::NTuple{2, Symbol}, len::Integer = 0; hostbuf = nothing)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:52.
│ Use `Buffer(#s19::Type{T}, ctx::Context, mem_flags::NTuple{2, Symbol}, len::Integer = 0; hostbuf = nothing) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:52
┌ Warning: Deprecated syntax `parametric method syntax Buffer{T}(::Type{T}, ctx::Context, flags::CL_mem_flags, len::Integer = 0; hostbuf::Union{Nothing, Array{T}} = nothing)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:93.
│ Use `Buffer(#s192::Type{T}, ctx::Context, flags::CL_mem_flags, len::Integer = 0; hostbuf::Union{Nothing, Array{T}} = nothing) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:93
┌ Warning: Deprecated syntax `parametric method syntax enqueue_read_buffer{T}(q::CmdQueue, buf::Buffer{T}, hostbuf::Array{T}, dev_offset::Csize_t, wait_for::Union{Nothing, Vector{Event}}, is_blocking::Bool)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:148.
│ Use `enqueue_read_buffer(q::CmdQueue, buf::Buffer{T}, hostbuf::Array{T}, dev_offset::Csize_t, wait_for::Union{Nothing, Vector{Event}}, is_blocking::Bool) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:148
┌ Warning: Deprecated syntax `parametric method syntax enqueue_write_buffer{T}(q::CmdQueue, buf::Buffer{T}, hostbuf::Array{T}, byte_count::Csize_t, offset::Csize_t, wait_for::Union{Nothing, Vector{Event}}, is_blocking::Bool)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:167.
│ Use `enqueue_write_buffer(q::CmdQueue, buf::Buffer{T}, hostbuf::Array{T}, byte_count::Csize_t, offset::Csize_t, wait_for::Union{Nothing, Vector{Event}}, is_blocking::Bool) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:167
┌ Warning: Deprecated syntax `parametric method syntax enqueue_copy_buffer{T}(q::CmdQueue, src::Buffer{T}, dst::Buffer{T}, byte_count::Csize_t, src_offset::Csize_t, dst_offset::Csize_t, wait_for::Union{Nothing, Vector{Event}})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:186.
│ Use `enqueue_copy_buffer(q::CmdQueue, src::Buffer{T}, dst::Buffer{T}, byte_count::Csize_t, src_offset::Csize_t, dst_offset::Csize_t, wait_for::Union{Nothing, Vector{Event}}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:186
┌ Warning: Deprecated syntax `parametric method syntax enqueue_unmap_mem{T}(q::CmdQueue, b::Buffer{T}, a::Array{T}; wait_for = nothing)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:213.
│ Use `enqueue_unmap_mem(q::CmdQueue, b::Buffer{T}, a::Array{T}; wait_for = nothing) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:213
┌ Warning: Deprecated syntax `parametric method syntax unmap!{T}(q::CmdQueue, b::Buffer{T}, a::Array{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:241.
│ Use `unmap!(q::CmdQueue, b::Buffer{T}, a::Array{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:241
┌ Warning: Deprecated syntax `parametric method syntax enqueue_map_mem{T}(q::CmdQueue, b::Buffer{T}, flags::Symbol, offset::Integer, dims::Dims, wait_for = nothing, is_blocking = false)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:254.
│ Use `enqueue_map_mem(q::CmdQueue, b::Buffer{T}, flags::Symbol, offset::Integer, dims::Dims, wait_for = nothing, is_blocking = false) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:254
┌ Warning: Deprecated syntax `parametric method syntax enqueue_map_mem{T}(q::CmdQueue, b::Buffer{T}, flags::CL_map_flags, offset::Integer, dims::Dims, wait_for = nothing, is_blocking = false)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:275.
│ Use `enqueue_map_mem(q::CmdQueue, b::Buffer{T}, flags::CL_map_flags, offset::Integer, dims::Dims, wait_for = nothing, is_blocking = false) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:275
┌ Warning: Deprecated syntax `parametric method syntax enqueue_fill_buffer{T}(q::CmdQueue, buf::Buffer{T}, pattern::T, offset::Csize_t, nbytes::Csize_t, wait_for::Union{Vector{Event}, Nothing})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:324.
│ Use `enqueue_fill_buffer(q::CmdQueue, buf::Buffer{T}, pattern::T, offset::Csize_t, nbytes::Csize_t, wait_for::Union{Vector{Event}, Nothing}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:324
┌ Warning: Deprecated syntax `parametric method syntax enqueue_fill{T}(q::CmdQueue, buf::Buffer{T}, x::T)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:342.
│ Use `enqueue_fill(q::CmdQueue, buf::Buffer{T}, x::T) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:342
┌ Warning: Deprecated syntax `parametric method syntax fill!{T}(q::CmdQueue, buf::Buffer{T}, x::T)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:350.
│ Use `fill!(q::CmdQueue, buf::Buffer{T}, x::T) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:350
┌ Warning: Deprecated syntax `parametric method syntax Base.copy!{T}(q::CmdQueue, dst::Array{T}, src::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:358.
│ Use `Base.copy!(q::CmdQueue, dst::Array{T}, src::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:358
┌ Warning: Deprecated syntax `parametric method syntax Base.copy!{T}(q::CmdQueue, dst::Buffer{T}, src::Array{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:367.
│ Use `Base.copy!(q::CmdQueue, dst::Buffer{T}, src::Array{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:367
┌ Warning: Deprecated syntax `parametric method syntax Base.copy!{T}(q::CmdQueue, dst::Buffer{T}, src::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:377.
│ Use `Base.copy!(q::CmdQueue, dst::Buffer{T}, src::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:377
┌ Warning: Deprecated syntax `parametric method syntax Base.copy{T}(q::CmdQueue, src::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:389.
│ Use `Base.copy(q::CmdQueue, src::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:389
┌ Warning: Deprecated syntax `parametric method syntax empty_like{T}(ctx::Context, b::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:397.
│ Use `empty_like(ctx::Context, b::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:397
┌ Warning: Deprecated syntax `parametric method syntax empty_like{T}(ctx::Context, a::Array{T}, flag::Symbol = :rw)` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:410.
│ Use `empty_like(ctx::Context, a::Array{T}, flag::Symbol = :rw) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:410
┌ Warning: Deprecated syntax `parametric method syntax write!{T}(q::CmdQueue, buf::Buffer{T}, hostbuf::Array{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:416.
│ Use `write!(q::CmdQueue, buf::Buffer{T}, hostbuf::Array{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:416
┌ Warning: Deprecated syntax `parametric method syntax read{T}(q::CmdQueue, buf::Buffer{T})` around /home/juliohm/.julia/dev/OpenCL/src/buffer.jl:423.
│ Use `read(q::CmdQueue, buf::Buffer{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/buffer.jl:423
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/program.jl:5.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/program.jl:5
┌ Warning: Package OpenCL does not have Printf in its dependencies:
│ - If you have OpenCL checked out for development and have
│   added Printf as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with OpenCL
└ Loading Printf into OpenCL from project dependency, future warnings for OpenCL are suppressed.
┌ Warning: Deprecated syntax `implicit assignment to global variable `num_devices``.
│ Use `global num_devices` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `num_devices``.
│ Use `global num_devices` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `devices``.
│ Use `global devices` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `devices``.
│ Use `global devices` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `context``.
│ Use `global context` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `context``.
│ Use `global context` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:2.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:2
┌ Warning: Deprecated syntax `parametric method syntax LocalMem{T}(::Type{T}, len::Integer)` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:50.
│ Use `LocalMem(#unused#::Type{T}, len::Integer) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:50
┌ Warning: Deprecated syntax `parametric method syntax Base.eltype{T}(l::LocalMem{T})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:56.
│ Use `Base.eltype(l::LocalMem{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:56
┌ Warning: Deprecated syntax `parametric method syntax Base.sizeof{T}(l::LocalMem{T})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:57.
│ Use `Base.sizeof(l::LocalMem{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:57
┌ Warning: Deprecated syntax `parametric method syntax Base.length{T}(l::LocalMem{T})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:58.
│ Use `Base.length(l::LocalMem{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:58
┌ Warning: Deprecated syntax `parametric method syntax _contains_different_layout{T}(::Type{T})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:87.
│ Use `_contains_different_layout(#unused#::Type{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:87
┌ Warning: Deprecated syntax `parametric method syntax contains_different_layout{T <: Union{Float32, Float64, Int8, Int32, Int64, UInt8, UInt32, UInt64}}(::Type{NTuple{3, T}})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:96.
│ Use `contains_different_layout(#unused#::Type{NTuple{3, T}}) where T <: Union{Float32, Float64, Int8, Int32, Int64, UInt8, UInt32, UInt64}` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:96
┌ Warning: Deprecated syntax `parametric method syntax contains_different_layout{T}(::Type{T})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:108.
│ Use `contains_different_layout(#unused#::Type{T}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:108
┌ Warning: Deprecated syntax `parametric method syntax struct2tuple{T}(x::T)` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:112.
│ Use `struct2tuple(x::T) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:112
┌ Warning: Deprecated syntax `parametric method syntax replace_different_layout{T}(x::T)` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:124.
│ Use `replace_different_layout(x::T) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:124
┌ Warning: Deprecated syntax `parametric method syntax replace_different_layout{N}(red::NTuple{N, Any}, rest::Tuple{})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:134.
│ Use `replace_different_layout(red::NTuple{N, Any}, rest::Tuple{}) where N` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:134
┌ Warning: Deprecated syntax `parametric method syntax replace_different_layout{N}(red::NTuple{N, Any}, rest)` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:136.
│ Use `replace_different_layout(red::NTuple{N, Any}, rest) where N` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:136
┌ Warning: Deprecated syntax `parametric method syntax replace_different_layout{T <: Union{Float32, Float64, Int8, Int32, Int64, UInt8, UInt32, UInt64}}(arg::NTuple{3, T})` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:151.
│ Use `replace_different_layout(arg::NTuple{3, T}) where T <: Union{Float32, Float64, Int8, Int32, Int64, UInt8, UInt32, UInt64}` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:151
┌ Warning: Deprecated syntax `parametric method syntax to_cl_ref{T}(arg::T)` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:156.
│ Use `to_cl_ref(arg::T) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:156
┌ Warning: Deprecated syntax `parametric method syntax set_arg!{T}(k::Kernel, idx::Integer, arg::T)` around /home/juliohm/.julia/dev/OpenCL/src/kernel.jl:182.
│ Use `set_arg!(k::Kernel, idx::Integer, arg::T) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/kernel.jl:182
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `implicit assignment to global variable `info``.
│ Use `global info` instead.
└ @ none:0
┌ Warning: Deprecated syntax `type` at /home/juliohm/.julia/dev/OpenCL/src/array.jl:3.
│ Use `mutable struct` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:3
┌ Warning: Deprecated syntax `parametric method syntax CLArray{T}(buf::Buffer{T}, queue::CmdQueue, sz::Tuple{Vararg{Int}})` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:16.
│ Use `CLArray(buf::Buffer{T}, queue::CmdQueue, sz::Tuple{Vararg{Int}}) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:16
┌ Warning: Deprecated syntax `parametric method syntax CLArray{T, N}(queue::CmdQueue, flags::Tuple{Vararg{Symbol}}, hostarray::AbstractArray{T, N})` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:23.
│ Use `CLArray(queue::CmdQueue, flags::Tuple{Vararg{Symbol}}, hostarray::AbstractArray{T, N}) where {T, N}` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:23
┌ Warning: Deprecated syntax `parametric method syntax CLArray{T, N}(queue::CmdQueue, hostarray::AbstractArray{T, N}; flags = (:rw, :copy))` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:31.
│ Use `CLArray(queue::CmdQueue, hostarray::AbstractArray{T, N}; flags = (:rw, :copy)) where {T, N}` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:31
┌ Warning: Deprecated syntax `parametric method syntax Base.deepcopy{T, N}(A::CLArray{T, N})` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:42.
│ Use `Base.deepcopy(A::CLArray{T, N}) where {T, N}` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:42
┌ Warning: Deprecated syntax `parametric method syntax Base.fill{T}(::Type{T}, q::CmdQueue, x::T, dims...)` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:52.
│ Use `Base.fill(#unused#::Type{T}, q::CmdQueue, x::T, dims...) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:52
┌ Warning: Deprecated syntax `parametric method syntax Base.zeros{T}(::Type{T}, q::CmdQueue, dims...)` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:63.
│ Use `Base.zeros(#unused#::Type{T}, q::CmdQueue, dims...) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:63
┌ Warning: Deprecated syntax `parametric method syntax Base.ones{T}(::Type{T}, q::CmdQueue, dims...)` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:65.
│ Use `Base.ones(#unused#::Type{T}, q::CmdQueue, dims...) where T` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:65
┌ Warning: Deprecated syntax `parametric method syntax Base.eltype{T, N}(A::CLArray{T, N})` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:75.
│ Use `Base.eltype(A::CLArray{T, N}) where {T, N}` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:75
┌ Warning: Deprecated syntax `parametric method syntax Base.show{T, N}(io::IO, A::CLArray{T, N})` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:89.
│ Use `Base.show(io::IO, A::CLArray{T, N}) where {T, N}` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:89
┌ Warning: Deprecated syntax `parametric method syntax to_host{T, N}(A::CLArray{T, N},; queue = A.queue)` around /home/juliohm/.julia/dev/OpenCL/src/array.jl:95.
│ Use `to_host(A::CLArray{T, N},; queue = A.queue) where {T, N}` instead.
└ @ ~/.julia/dev/OpenCL/src/array.jl:95
```

Could you please merge this and enable femtocleaner to update the rest of the code?

**Comment by maleadt** [comment]
Enabled CI and ran FemtoCleaner on master, please rebase.

**Comment by maleadt** [comment]
Oh right, gitlab doesn't run on external PRs such as yours... Let me know when this passes tests locally, and we'll merge to see the CI status on the `master` branch. It's the best we can do right now.

**Comment by juliohm** [comment]
For some reason Libdl is causing trouble now. It was working before after a `Pkg.resolve()` locally. I am trying to figure out before I push a few more commits.

**Comment by maleadt** [comment]
Remember that stdlib deps also need to listed in the Project.toml now.

**Comment by juliohm** [comment]
But we still have REQUIRE here right as a backward compatible mode? I am not listing stdlibs explicitly in any of my packages and they are all working fine.

**Comment by maleadt** [comment]
For CI to work properly.

**Comment by juliohm** [comment]
I don't know how to use Project.toml yet, could you maybe push a commit to this PR with the necessary change?

**Comment by maleadt** [comment]
Just open a terminal in the repo folder, do `julia --project`, hit `]` to enter Pkg3, and do `add Libdl` and others. It'll update the Project.toml automatically.

**Comment by juliohm** [comment]
Nice! Liked this. Pushing another commit...

**Comment by juliohm** [comment]
@maleadt could you please check the remaining error message? This one I have no idea how to fix.

Also, we need to take care of the other warnings that femtocleaner missed.

**Comment by maleadt** [comment]
> @maleadt could you please check the remaining error message? This one I have no idea how to fix.

As I mentioned on Slack, I really have no time to help out with this right now.

**Comment by juliohm** [comment]
Thank you, I appreciate it.

**Comment by juliohm** [comment]
Superseded by #169

**Pull request closed without merging**
